force-app/main/default/objects/Tv_Serie__c/Tv_Serie__c.object-meta.xml
<CustomObject>
    <label>Tv Serie</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tv Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tv_Serie__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Adventure</fullName>
            </value>
            <value>
                <fullName>Comedy</fullName>
            </value>
            <value>
                <fullName>Drama</fullName>
            </value>
            <value>
                <fullName>Fantasy</fullName>
            </value>
            <value>
                <fullName>Horror</fullName>
            </value>
            <value>
                <fullName>Science Fiction</fullName>
            </value>
            <value>
                <fullName>Western</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tv_Serie__c/fields/Directors__c.field-meta.xml
<CustomField>
    <fullName>Directors__c</fullName>
    <label>Directors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tv_Serie__c/fields/Logo_url__c.field-meta.xml
<CustomField>
    <fullName>Logo_url__c</fullName>
    <label>Logo url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tv_Serie__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>Rate from 1 to 10, 1 being terrible and 10 being amazing.</description>
    <label>Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TvSeriesController.cls
public with sharing class TvSeriesController {

    @AuraEnabled(cacheable=true scope='global')
    public static Tv_Serie__c[] getTvSerie(String tvSerieId) {
        return [
            SELECT
            Id,
            Name,
            Rate__c,
            Category__c,
            Logo_url__c,
            Description__c,
            Directors__c
            FROM Tv_Serie__c
            WHERE Id =: tvSerieId
        ];
    }

    @AuraEnabled(cacheable=true scope='global')
    public static Tv_Serie__c[] getAllTvSeries() {
        return [
            SELECT
                Id,
                Name,
                Rate__c,
                Category__c,
                Description__c,
                Logo_url__c,
                Directors__c
            FROM Tv_Serie__c
        ];
    }

    @AuraEnabled(cacheable=true scope='global')
    public static Tv_Serie__c[] searchTvSerie(String searchTerm) {
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllTvSeries();
        }
        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        return [
            SELECT
            Id,
            Name,
            Rate__c,
            Category__c,
            Directors__c
            FROM Tv_Serie__c
            WHERE Name LIKE :searchTerm
            WITH SECURITY_ENFORCED
            ORDER BY Name
            LIMIT 50
        ];
    }
}